### PR TITLE
Bundle json decoder

### PR DESCRIPTION
**Pull request by jinmel**

### CODE REVIEW

**Review by ferranbt — APPROVED** [review]

**Comment by jinmel** [comment]
@ferranbt ChatGPT related changes are failing only on the ci. Is there a way to fix this?

**Comment by jinmel** [comment]
@ferranbt how about skipping chatgpt unit test in ci?

**Comment by ferranbt** [comment]
> @ferranbt how about skipping chatgpt unit test in ci?

Nah, It should work, it passes on main branch. Please reset the key again.

**Comment by ferranbt** [comment]
I think I found the issue, If the PR comes from a fork, GitHub secrets are not loaded but the env var is set to empty. Could you do:
```
    function getChatGPT() public returns (ChatGPT chatgpt) {
        // NOTE: tried to do it with envOr but it did not worked
        try vm.envString("CHATGPT_API_KEY") returns (string memory apiKey) {
            if (apiKey.length == 0) {
                vm.skip(true);
                return;
            }
            chatgpt = new ChatGPT(apiKey);
        } catch {
            vm.skip(true);
        }
    }
```

**Comment by ferranbt** [comment]
Please rebase upstream and try again.

**Pull request merged**
