### PR TITLE
Suavex rpc request library

### PR DESCRIPTION
**Pull request by jinmel**

### CODE REVIEW

**Review by lthibault — APPROVED** [review]
LGTM.

**Review by ferranbt — CHANGES_REQUESTED** [review]
As with the convo we had over Slack, this is not necessary anymore because we would likely migrate to builder API and builder API in suave-std before we need to have `buildEthByBlock` here.

**Comment by zeroXbrock** [comment]
> Could we merge some of this with #57

merged this into #57 to replace the contents of the encoding methods in the `Bundle` lib

**Comment by jinmel** [comment]
closing this issue by merge with #57

**Pull request closed without merging**
